# Generated by Django 4.0.2 on 2022-03-05 09:19

import annotator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_projectinvite_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=annotator.models.Image.image_path),
        ),
    ]
