# Generated by Django 4.0.2 on 2022-03-05 10:15

import annotator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_remove_image_image_path_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='annotation_file_path',
        ),
        migrations.AddField(
            model_name='project',
            name='annotation',
            field=models.FileField(blank=True, null=True, upload_to=annotator.models.Project.annotation_path),
        ),
    ]
