# Generated by Django 4.0.2 on 2022-03-12 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0006_rename_project_id_annotationclass_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvite',
            unique_together={('project', 'recipient_annotator')},
        ),
    ]
