# Generated by Django 4.0.2 on 2022-03-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_alter_projectinvite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotation_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.annotationclass'),
        ),
    ]
