# Generated by Django 4.0.2 on 2022-03-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_image_annotation_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='isAnnotated',
        ),
        migrations.AlterField(
            model_name='image',
            name='annotation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.annotationclass'),
        ),
    ]
