# Generated by Django 4.0.2 on 2022-03-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0009_remove_image_isannotated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='assigned_annotator',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'annotator_user_group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
