# Generated by Django 4.0.2 on 2022-05-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_image_assigned_annotator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.CharField(choices=[('CF', 'Image Classification'), ('BB', 'Bounding Box'), ('BE', 'Bounding Ellipse'), ('BP', 'Bounding Polygon'), ('FH', 'Freehand'), ('LN', 'Line'), ('KP', 'Key Point')], default='CF', max_length=200),
        ),
    ]
