# Generated by Django 4.0.2 on 2022-05-16 08:43

import annotator.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_alter_annotationtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage, upload_to=annotator.models.Project.annotation_path),
        ),
    ]
