# Generated by Django 4.0.2 on 2022-05-19 11:21

import annotator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0012_alter_project_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='machine_learning_model',
            field=models.FileField(blank=True, null=True, upload_to=annotator.models.Project.machine_learning_model_path),
        ),
    ]
